### ISSUE TITLE
Missing "server_info_dir" and "local_dataowner_info_dir" in config.py

### ISSUE THREAD

**Issue by rayrayraykk** [zkhku/fedsage#1]

**Comment by youngfish42** [comment]
server_info_dir=root_path +"global_result/server_info/" + dataset+"_"+str(num_owners)+'.h5' 
local_dataowner_info_dir=root_path +"dataowner/"+ dataset+"_"+str(num_owners)

**Comment by youngfish42** [comment]
> server_info_dir=root_path +"global_result/server_info/" + dataset+"_"+str(num_owners)+'.h5' local_dataowner_info_dir=root_path +"dataowner/"+ dataset+"_"+str(num_owners)

https://github.com/zkhku/fedsage/commit/096974991ed66d9e6c4a6d5e6a67afdc518ed316

**Comment by zkhku** [comment]
Thanks for pointing out! Now these two paths are in config.py.

**Comment by zkhku** [comment]
> Thanks for pointing out! Now these two paths are in config.py.

You need to locally create respective directories if you want to save any files under which. To match the current config.py, I manually add "global_result/server_info/" and "dataowner/" within the project.
